overrides: coala.yaml

name: documentation

docs_dir: ./.

dependencies:
  - coala
  - '-r docs-requirements.txt'

configuration:
  template_dir:
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - requirements.txt: requirements.txt.jj2
  - netlify.toml: docs/netlify.toml.jj2
copy:
  - docs-requirements.txt: docs/docs-requirements.txt
  - runtime.txt: runtime.txt
  - Makefile: docs/Makefile
  - make.bat: docs/make.bat
  - _static/custom.css: docs/custom.css
  - _static/images/coala-header.png: docs/images/coala-header.png
  - _static/images/coala_logo.svg: docs/images/coala_logo.svg
